CREATE TABLE `dnd`.`characters` (
  `userName` VARCHAR(45) NOT NULL,
  `password` VARCHAR(20) NOT NULL,
  `charName` VARCHAR(45) NULL,
  `class` VARCHAR(45) NULL,
  `race` VARCHAR(45) NULL,
  `alignment` VARCHAR(45) NULL,
  `exp` MEDIUMINT(9) UNSIGNED NULL,
  `armorClass` TINYINT(2) UNSIGNED NULL,
  `strength` TINYINT(2) UNSIGNED NULL,
  `dexterity` TINYINT(2) UNSIGNED NULL,
  `constitution` TINYINT(2) UNSIGNED NULL,
  `intelligence` TINYINT(2) UNSIGNED NULL,
  `wisdom` TINYINT(2) UNSIGNED NULL,
  `charisma` TINYINT(2) UNSIGNED NULL,
  `level` TINYINT(2) UNSIGNED NULL,
  `hitPoints` MEDIUMINT(3) NULL,
  `hitDice` VARCHAR(45) NULL,
  `speed` TINYINT(2) UNSIGNED NULL,
  `initiative` TINYINT(2) UNSIGNED NULL,
  `copper` INT(10) UNSIGNED NULL,
  `silver` INT(10) UNSIGNED NULL,
  `gold` INT(10) UNSIGNED NULL,
  `platinum` INT(10) UNSIGNED NULL,
  `proficiency` TINYINT(2) UNSIGNED NULL,
  `feats` BLOB NULL,
  `inventory` BLOB NULL,
  `weapons` VARCHAR(255) NULL,
  `weaponTypes` VARCHAR(45) NULL,
  `weaponRanges` VARCHAR(45) NULL,
  `weaponDamages` VARCHAR(45) NULL,
  `storyNotes` BLOB NULL,
  `other` BLOB NULL,
  PRIMARY KEY (`userName`)
);